### ISSUE TITLE
go2rtc autopause

### ISSUE THREAD

**Issue by jfalgon** [AlexxIT/go2rtc#1515]
Hello

I'm facing an issue with go2rtc ; Maybe it's not related to it but All my cameras are having this kind of behaviour. They switch to pause during the live

is there an explanation to this ? (Network issue, cpu/ram server issue, misconfiguration ...) ?

That's so sad because go2rtc seems to provide very good quality with low latency :)

![image](https://github.com/user-attachments/assets/1683b12d-2e59-47f4-bfb9-ce101ec23a2e)

**Comment by AlexxIT** [comment]
Looks like you using MSE technology. Because you have while time line. This is a normal situation for MSE in poor channel conditions. Should be solved on the client side (JavaScript). Perhaps there are others issues about such an improvement.

WebRTC technology works well in poor connection conditions. Without any additional modifications on the client side.
