### ISSUE TITLE
Add support insecure HTTPS client

### ISSUE THREAD

**Issue by airdamien** [AlexxIT/go2rtc#343]
The cameras auto-redirect to https if hit from http://

2023-04-08 22:58:08.633036685  18:58:08.632 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"https://<REDACTED>/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=<REDACTED>&password=<REDACTED>\": x509: cannot validate certificate for 10.50.0.174 because it doesn't contain any IP SANs"

tx

**Comment by NickM-27** [comment]
You need to enable http in the cameras network settings

**Comment by airdamien** [comment]
@NickM-27 ah, have to enable DDNS floppy before advanced gives you the option to enable http. I think it's still useful to have https and not require full validation.  

tx.

**Comment by mew1033** [comment]
I just ran into this as well. Would love to be able to ignore certificates for cameras. Bonus points if we could pin the certificate in the config so only that cert is allowed.

**Comment by AlexxIT** [comment]
This issue only for HTTPS. RTSPS already has this feature.

**Comment by mew1033** [comment]
I'm accessing my reolink cameras via HTTPS. I read something (https://docs.frigate.video/configuration/camera_specific/#reolink-cameras) that indicated that was the optimal way of accessing them. HTTP as mentioned at that link didn't work at first, then I realized I had turned off HTTP access entirely in favor of HTTPS. I turned it back on so that I could still use HTTP, but I'd like to turn it back off.

However, if accessing my reolink camera (Reolink Duo in this case) is better done by another method, that'd be fine too. I honestly have no idea which method is best and would defer to the experts on that.

Thanks!
