### ISSUE TITLE
go2rtc running on Unraid - fails to playback WebRTC for 3 out of 4 Ring cameras.

### ISSUE THREAD

**Issue by Scope666** [AlexxIT/go2rtc#492]
I've been working with @tsightler on this [issue](https://github.com/tsightler/ring-mqtt/issues/653) for awhile now, and we seem to have narrowed it down to go2rtc running on the latest version of Unraid.

Setup is:

Home Assistant running in Unraid - Docker with
RTSPtoWebRTC built-in integration
ring-mqtt running in Unraid - Docker
go2rtc running in Unraid - Docker
4 Ring devices.  A doorbell Pro, an older Floodlight, a Spotlight, and a newer Floodlight Plus

Up until recently everything worked perfectly.  Now only 1 of the 4 cameras is able to playback in Home Assistant.  Using the go2rtc web interface, all streams can playback in MSE mode, but only the one camera can do WebRTC.

Running go2rtc on a different computer (Windows 11) didn't have the problem at all, so seems like a compatibility issue with Unraid.  Also RTSPtoWEB is able to play all cameras in WebRTC without issue on the same Unraid Server.

There's a ton of additional detail in the original ring-mqtt Issue linked above.

**Comment by AlexxIT** [comment]
So earlier all was fine. And from some moment only 1 camera can use WebRTC mode?

**Comment by Scope666** [comment]
Exactly ... I had this setup up and running and everything worked perfectly.  My suspicion is something changed in the Docker networking environment with the recent Unraid versions.

The one difference with the working camera that @tsightler and I caught was that it was negotiating a lower H.264 level ... usually 3.2 or 4.0 Main .... while the 3 "bad" cameras were 4.1 High.

**Comment by AlexxIT** [comment]
Do your problem cameras have a high bitrate?

**Comment by Scope666** [comment]
I don't think so, they're all close to 5 years old, none of them offer the "Legacy Video Mode" in the Ring App, suggesting that they don't support H.265 like newer Ring cameras do.

**Comment by Scope666** [comment]
Update, I just downgraded Unraid back to 6.11.5 which was released last November, a known "working good" version and the behavior hasn't changed.  I'm wondering if the problem is caused by something Ring recently changed...

**Comment by marcob79** [comment]
How you can say that that switch is the problem?

**Comment by Scope666** [comment]
> How you can say that that switch is the problem?

Because all the cameras work with WebRTC when I swap it out with something else.  @tsightler has a theory (that I agree with) that the switch doesn't have a large enough buffer to handle the bursty nature of the way the traffic comes in from Ring.

**Comment by tsightler** [comment]
To add some detail, I don't really know why a specific switch would cause any problems, especially with 3 streams not working and 1 working, but there are some more potential clues.

@AlexxIT Asked about bitrate above.  Well, Ring cameras have a notoriously low bitrate overall, averaging only ~2.5Mb for most cameras, they use a dynamic bitrate so sometimes it's even less.

@Scope666 had one live stream that did work and 3 that did not.  The one that did work appeared to be negotiating a slightly lower H.264 profile, main profile level 3.1 vs the other three cameras, which negotiated high profile level 4.1.  Now, I wouldn't expect this to have a huge impact on the bitrate, but almost certainly it was a little bit lower.

But, there is even more evidence that bitrate is somehow involved in the failure.  The ring-mqtt code also includes the ability to play back recorded video streams.  Ring offers both raw video recording (exactly as the camera recorded it) and "transcoded" videos, the latter of which can be optimized to be downloaded and played back locally.  These transcoded videos include things like timestamps, etc.

These videos are generally the same, or even slightly lower bitrate than the original recording, but because they are optimized for downloading, they don't stream very well,  When a user requests to stream them, I overcome this by using ffmpeg to stream the file directly from the S3 storage over HTTPS, and then retranscoding the file on the fly, however, because my project runs commonly on low-end hardware like RPi's, and I can't be sure the code has access to hardware acceleration, I use the ultrafast profile instead, which of course trades CPU for size, creating significantly higher bitrate files, usually around 10-12Mb.

So, with this switch in place there are 7 out of 8 streams that won''t play back:

4 event streams at ~10-12Mb won't play back
3 live streams at ~2.5Mb won't play back
1 live stream at slightly lower bitrate (unconfirmed), that does play back

However, once the switch was removed from the environment, all 8 streams play back fine with no other changes.  This seems to indicate something with the switch, perhaps some unexpected interaction, etc.  I'm not 100% sure why a switch would have such behavior, but it is a small "smart" switch, with QoS and storm control.  I know these devices are regularly underpowered, have smaller buffers and processors than would be ideal, so my thought is that maybe this switch is just dropping too many UDP packets to get the stream started.  The one stream that worked was just slightly lower bitrate just below the threshold.  I certainly don't have any proof of this, was just trying to come up with a theory as to why a switch would impact 7 of 8 streams.

I'm certainly open to other theories.

**Comment by AlexxIT** [comment]
I plan to investigate the stability of the WebRTC UDP vs WebRTC TCP.

There is known problem with WebRTC UDP on hi bitrates
https://habr.com/en/companies/flashphoner/articles/480006/

**Comment by AlexxIT** [comment]
Latest version supports `webrtc/tcp` mode. It can be used with this integration https://github.com/AlexxIT/WebRTC

**Comment by cscoppafox** [comment]
Thanks for the update! ... I'm assuming you're talking about 3.2.1?  Do you have to do anything special to tell it to use TCP instead of UDP?  @tsightler Not sure what I would have to change on the ring-mqtt side to test this out.  (also the go2rtc cooked into your container)

**Comment by Scope666** [comment]
Thanks for the update! ... I'm assuming you're talking about 3.2.1? Do you have to do anything special to tell it to use TCP instead of UDP? @tsightler Not sure what I would have to change on the ring-mqtt side to test this out. (also the go2rtc cooked into your container)

btw, the article you linked above really did a good job explaining WHY this is happening. With a dumb switch it just works, but with the "smart" one, the qos, buffers, etc, can't handle the UDP at that resolution / bitrate / burstiness. At least with TCP it KNOWS the packet(s) was lost and retransmits.

"Why stream over TCP at all if there is UDP

This is a reasonable question to ask. The answer is, for pushing big resolutions through the channel. For example, in the case of VR (Virtual Reality) streaming the resolutions may begin from 4k. It does not seem possible to push a stream with such a resolution and with a bitrate of about 10 Mbps into a regular channel without losses, the server spits out the UDP packets and they begin to be lost in the network in bunches, then the remainder of them begins to be sent, and so on. Big amounts of discarded video packets corrupt the video, and the net result is that the quality becomes very poor. This is the reason why WebRTC over TCP is used for delivering the video in general purpose networks and with high resolutions, such as Full HD and 4k, in order to rule out network packet losses at the expense of a slight increase in the communication latency."

**Comment by tsightler** [comment]
>  @tsightler Not sure what I would have to change on the ring-mqtt side to test this out. (also the go2rtc cooked into your container)

No changes are needed since the go2rtc instance in the ring-mqtt container is used only as an RTSP proxy and does not provide WebRTC at all (it's actually disabled).

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
