### ISSUE TITLE
New build ETA? Roadmap?

### ISSUE THREAD

**Issue by Uriziel01** [AlexxIT/go2rtc#515]
TL;DR; any ETA on a new build? future roadmap?

Hi,
Last one is back from may and we have so many nice new fixes/improvements right now I think it would make sense, I know I can just build it on my own, it's just golang, but I'm asking about new precompiled binary in the repository artifacts.

Are you planning on any kind of future roadmap? I've went through few issues where you mentioned some of the requested features/fixes are planned but AFAIK there is no single place for users to check what are you cooking currently.

Thank you 😄

**Comment by AlexxIT** [comment]
Everything in the master version is planned for release in the near future. I have a lot of projects going on. I don't want to make any specific promises because I might fail.

Hass WebRTC integration depends on this release, so they need to be released at the same time.

Also, in the new release, I want to update the dependencies of external libraries and I need to check if something breaks from that.
