### ISSUE TITLE
Support HLS streaming

### ISSUE THREAD

**Issue by wvdeadhead** [AlexxIT/go2rtc#53]
Please consider adding the capability of an HLS output for direct streaming to Google Nest Hub/Google Chromecast devices.

**Comment by calisro** [comment]
But webrtc doesn't support HLS.  But I stream just fine to my Nest hub and other devices using this with ffmpeg to handle any codec corrections.

**Comment by wvdeadhead** [comment]
Would you mind sharing your config?  I want to stream directly from go2rtc to a Nest Hub via a script.  Currently, with either Dahua or Unifi cameras, there is significant video delay and no audio, although both types of cameras have supported AAC audio enabled.

My thought regarding HLS, it could be another transcoding flag and would allow for better compatibility with Chromecast devices of multiple generations.

**Comment by calisro** [comment]
It depends on what codecs the camera has.  If when streaming to the nest hub for example if there's no audio, then just concentrate on that part:

  kitchen_main:
    - rtsp://xxxxxx@10.100.1.133/h264Preview_01_main
    - ffmpeg:rtsp://xxxxx@10.100.1.133/h264Preview_01_main#audio=opus
That just adds the opus codec to the set of available codecs.  Opus should be usable on the nest hub.

**Comment by AlexxIT** [comment]
I don't like this format. Not suitable for real-time streaming. Maybe someday, but not in priority.

**Comment by luzik** [comment]
I believe that HLS is used as live attachments to IOS notification. With HA HLS, it take few seconds to load the stream, so we believe that go2rtc could improve HA in that field :)

**Comment by AlexxIT** [comment]
This is not HA or go2rtc problem. HLS format was build for streaming. Not for real-time streaming. LL-HLS has some improvement with delay. But it is very complicated and no so good as WebRTC at anyway.

**Comment by wvdeadhead** [comment]
Thanks for all the comments.  I was hoping to use go2rtc as a "universal" conversion that interfaces with everything... like the image on the main page.  No worries if HLS isn't an option, was just wishful thinking.

@calisro, I've tried configs identical to yours, with and without Opus, but no audio will play regardless.  Opus doesn't seem to be a valid MP4 or HLS audio container.

As much as I love Home Assistant, it's implementation of HLS (or streaming in general) isn't the greatest.  I have buffering issues and delay, unlike what I've experienced with either this or the previous project.

**Comment by AlexxIT** [comment]
The image on the home page shows HLS as the source. There is no lie there :)

**Comment by AlexxIT** [comment]
Supported in v1.1.0

**Comment by lindsaymarkward** [comment]
Hi. This issue is the closest I can find to my current problem.
I am using a Home Assistant (HA) rich iphone message notification with a camera. It works for my other cameras not using go2rtc (Reolink and a generic IP camera with RTSP).
When I send one of my go2rtc web cameras (USB web cams on a Raspberry Pi using RTSP), I get the following error instead of the camera image:

> HLS stream unavailable
> Got non-200 status code (502)

go2rtc version: 1.6.2
Config looks like: 

    streams:
      lounge: ffmpeg:device?video=0&resolution=1280x720#video=h264

I see above that this should be supported. I would appreciate any help on this matter, thank you!

**Comment by AlexxIT** [comment]
I don't understand where you get this error

**Comment by lindsaymarkward** [comment]
Thanks for the reply and thanks in advance for helping :) 
I see it instead on my iPhone or Apple Watch instead of the stream.
With my other cameras, I see the message text and an image from the camera. I can click on (long-press) the notification to see a live camera stream.
With my two go2rtc cameras, I get an image with this error text in red. 
I've attached screenshots from my phone.

![IMG_2884](https://github.com/AlexxIT/go2rtc/assets/7665042/14c547a0-ded7-4000-9b3f-385a8679f564)

![IMG_2885](https://github.com/AlexxIT/go2rtc/assets/7665042/1d0e8aee-2e98-4b8f-aaa1-b213d5d6ebb1)

**Comment by AlexxIT** [comment]
I think this message related to Hass and not related to go2rtc. This HLS not from go2rtc
