### ISSUE TITLE
Work as systemctl go2rtc.service

### ISSUE THREAD

**Issue by Sheredeka** [AlexxIT/go2rtc#616]
Hi all!

how to run binary go2rtc_linux_amd64 as system service?

im try:
```
[Unit]
Description=AlexxIT go2rtc
After=network.target

[Service]
Type=forking
PIDFile=/opt/go2rtc/go2rtc.pid
ExecStart=/opt/go2rtc/go2rtc_linux_amd64 -config /opt/go2rtc/go2rtc.yaml
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target
```
but service works until the first error message "WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225 > error="read tcp 192.168.19.149:8554->192.168.19.72:58590: i/o timeout"" then stop with error

How to config service for correct start/restart/stop ?

**Comment by felipecrs** [comment]
Isn't systemd responsible to restart it when it fails?

**Comment by felipecrs** [comment]
- BTW, related to https://github.com/AlexxIT/go2rtc/pull/440.

**Comment by felipecrs** [comment]
Also, if I were you I would definitely run it as a docker container (so that docker manages the service).

**Comment by AlexxIT** [comment]
I don't know. Prefer to run all software in the Docker. Your error not related with this issue.

**Comment by Sheredeka** [comment]
It's not about an error, it's about the ability to launch go2rtc as a service (daemon) in the background, which will restart automatically if stopped.
systemctl go2rtc start
systemctl go2rtc restart
systemctl go2rtc stop

**Comment by AlexxIT** [comment]
Well. I can't help you with this. Ask on some Linux forum

**Comment by jneilliii** [comment]
under service section can't you just add
```
Restart=always
RestartSec=10
```

**Comment by Spamfast** [comment]
By default go2rtc doesn't self-daemonize. So your `type` should be `type=simple` or `type=exec` and you should remove the `PIDfile` line as systemd will manage the PID itself.

Because by default go2rtc doesn't bind to ports <1024 it can and should be run as a non-privileged user. Hence the `DynamicUser` line. Alternatively you could create system user/group `go2rtc` and use them. That would allow you to have `go2rtc.yaml` only readable by that user which might be a good idea if it contains API or camera stream credentials.

Here's my `go2rtc.service`:

```
[Unit]
Description=Video transcoder using go2rtc
Documentation=https://go2rtc.com/ https://github.com/AlexxIT/go2rtc
After=network-online.target
Requisite=network-online.target

[Service]
Type=exec
ExecStart=/usr/local/sbin/go2rtc --config /etc/go2rtc.yaml
Environment="PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
Restart=always
RestartSec=5
DynamicUser=true

[Install]
WantedBy=multi-user.target
```

**Comment by maxromanovsky** [comment]
@Spamfast what about `-daemon` from https://github.com/AlexxIT/go2rtc/pull/963?

**Comment by Spamfast** [comment]
Looking at the description, you should be able to use `Type=forking` if you add `-daemon`  to the `ExecStart=` command line. You'll have to capture the PID output by the foreground process to a PID file, usually somewhere under `/run/` and then tell systemd where that is using `PIDFile=`. 

On the other hand, using foreground and `exec` means systemd handles the PID stuff for you.

As discussed elsewhere, the Poettering way seems to be to prevent service executables from self-daemonizing and have systemd handle the backgrounding. (Whatever happened to 'do one thing well' I wonder? ;-))

I'm not sure how the foreground process writing the PID to stdout interacts with the logging output from the background daemon - ask the man, use the source or suck it and see I guess.

BTW PID files are ephemeral so should go under `/run/` because on most systems that is a RAM filesystem whose contents vanishes upon reboot. You could use `/tmp/` in a pinch . `/opt/` is a terrible idea - usually this is used for out-of-distro package installation directories, not on-the-fly generated temporary files.
