### ISSUE TITLE
Restrict the selection of udp port for webrtc

### ISSUE THREAD

**Issue by RomchikL** [AlexxIT/go2rtc#8]
Is it possible to select a set of udp ports for webrtc (as in HA WebRTC udp port min-max)?
In docker I must publish all udp ports, but I can't predict a random port.

**Comment by AlexxIT** [comment]
Why you need fixed UDP port?

**Comment by RomchikL** [comment]
Not to fix, but to limit the choice (e.g., 50000-51000).
Or there is no need to open udp ports for WebRTC in docker?

**Comment by AlexxIT** [comment]
You need to read docs
https://github.com/AlexxIT/go2rtc#module-webrtc

**Comment by markfrancisonly** [comment]
Seconding this request. Limiting the go2rtc webrtc udp range is useful. I was forced to reconfigure my firewall, opening every udp port to go2rtc when testing a migration from RTSPtoWebRTC.  Requiring every udp port to be open is undesirable.

btw, I can't get the documented TCP static public IP-address webrtc configuration to send the public ip address candidate. when configured, go2rtc only emits private-address:8555 instead of public-address:8555

**Comment by AlexxIT** [comment]
Public TCP should work. You can enable trace log level for WebRTC and check all IP address that sends by go2rtc.

**Comment by markfrancisonly** [comment]
observing candidates emitted from a retrofitted [ha webrtc-card card js client](https://github.com/markfrancisonly/go2rtc/blob/ha-webrtc-camera/ha-webrtc-camera/webrtc-camera.js) connecting to a go2rtc instance hosted as a docker container. I needed to modify the go2rtc ws api [removing origin checking](https://github.com/markfrancisonly/go2rtc/commit/f87bcb98d72a18c2c1db78277dae1baefb23386e) to get the modified card to work.

my go2rtc docker image is based @felipecrs's [PR](https://github.com/AlexxIT/go2rtc/pull/72) which builds go2rtc from my local git repository instead of pulling code live from the main repo....

how do I enable server-side webrtc tracing?

**Comment by AlexxIT** [comment]
WebRTC now uses single 8555 TCP and UDP port by default and for all connections
https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.8
